// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_QOGrIxKN1f8aE6D5Zha0Jnj2UdvcTDU',
    appId: '1:618257202616:web:68ddce6ddf01a4430ce34d',
    messagingSenderId: '618257202616',
    projectId: 'todo-baaa5',
    authDomain: 'todo-baaa5.firebaseapp.com',
    storageBucket: 'todo-baaa5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcGVqmcEBWwIASYIi5xADgKx0DTpmW_9o',
    appId: '1:618257202616:android:4967936a96e62c020ce34d',
    messagingSenderId: '618257202616',
    projectId: 'todo-baaa5',
    storageBucket: 'todo-baaa5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCeJQVrLeTWQfXThGHFK7FVqFqvB6QVrU',
    appId: '1:618257202616:ios:4337d8be86fae44a0ce34d',
    messagingSenderId: '618257202616',
    projectId: 'todo-baaa5',
    storageBucket: 'todo-baaa5.firebasestorage.app',
    androidClientId: '618257202616-t3q25a5o4mp0n1jmnon40fhk92d32cv1.apps.googleusercontent.com',
    iosClientId: '618257202616-vu4mar01kkvd2idu7lilu5qe6h6fim3i.apps.googleusercontent.com',
    iosBundleId: 'com.gobi.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCeJQVrLeTWQfXThGHFK7FVqFqvB6QVrU',
    appId: '1:618257202616:ios:4337d8be86fae44a0ce34d',
    messagingSenderId: '618257202616',
    projectId: 'todo-baaa5',
    storageBucket: 'todo-baaa5.firebasestorage.app',
    androidClientId: '618257202616-t3q25a5o4mp0n1jmnon40fhk92d32cv1.apps.googleusercontent.com',
    iosClientId: '618257202616-vu4mar01kkvd2idu7lilu5qe6h6fim3i.apps.googleusercontent.com',
    iosBundleId: 'com.gobi.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_QOGrIxKN1f8aE6D5Zha0Jnj2UdvcTDU',
    appId: '1:618257202616:web:d3957f76d610554c0ce34d',
    messagingSenderId: '618257202616',
    projectId: 'todo-baaa5',
    authDomain: 'todo-baaa5.firebaseapp.com',
    storageBucket: 'todo-baaa5.firebasestorage.app',
  );
}
